version: '2'

services:
  mysql:
    image: 'mysql:5.7'
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/var/lib/mysql'

volumes:
  mysql_data:
    driver: local

networks:
  default:
    external:
      name: purasu-local
